name: Android CI & Firebase App Distribution

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

env:
  BUILD_TYPE: Release

jobs:
  build_and_distribute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      run: |
        echo "$ENCRYPTED_KEYSTORE_FILE" | base64 --decode > my-upload-key.keystore
      env:
        ENCRYPTED_KEYSTORE_FILE: ${{ secrets.ENCRYPTED_KEYSTORE_FILE }}

    - name: Build Release APK
      run: |
        ./gradlew assembleRelease
      env:
        KEYSTORE_PATH: my-upload-key.keystore
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Upload to Firebase App Distribution
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
        channelId: 'github-actions'
        target: 'app-distribution'
        apkPath: 'app/build/outputs/apk/release/app-release.apk'
        appId: 'YOUR_FIREBASE_APP_ID' # Replace with your Android app ID from Firebase
        groups: 'testers' # Optional: comma-separated list of tester groups
        releaseNotes: 'Automated build from GitHub Actions' # Optional: release notes


